# MCU name
MCU = RP2040

# Bootloader selection
BOOTLOADER = rp2040
BOARD = GENERIC_RP_RP2040
SERIAL_DRIVER = vendor

EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

CAPS_WORD_ENABLE = yes
UNICODE_COMMON = yes
UNICODEMAP_ENABLE = yes
COMBO_ENABLE = yes

SPLIT_KEYBOARD = yes
