OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
AUDIO_ENABLE = no
MUSIC_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
CAPS_WORD_ENABLE = yes
UNICODE_COMMON = yes
UNICODEMAP_ENABLE = yes
COMBO_ENABLE = yes

#HAPTIC FEEBACK
HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no
